-- Generated from generator/demo_specs/aws-malaysia-palm-oil-eudr.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-malaysia-palm-oil-eudr
-- This is the schema that is actually deployed for MY_PALM_OIL_EUDR.

-- Alerts fire on the bottom tail of EUDR Compliant
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_EUDR_COMPLIANT) AS T
  FROM RAW.SUPPLY_CHAIN_EVENTS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_EUDR_COMPLIANT <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_EUDR_COMPLIANT), 2) AS AVG_EUDR_COMPLIANT,
  ROUND(AVG(f.KPI_MSPO_CERTIFIED), 2) AS AVG_MSPO_CERTIFIED,
  ROUND(AVG(f.KPI_DUE_DILIGENCE_PENDING), 2) AS AVG_DUE_DILIGENCE_PENDING,
  ROUND(AVG(f.KPI_SATELLITE_MONITORING), 2) AS AVG_SATELLITE_MONITORING,
  ROUND(AVG(f.KPI_DEFORESTATION_FREE), 2) AS AVG_DEFORESTATION_FREE,
  ROUND(AVG(f.KPI_GPS_MAPPED_PLOTS), 2) AS AVG_GPS_MAPPED_PLOTS
FROM RAW.SUPPLY_CHAIN_EVENTS f
JOIN RAW.MPOB_REFERENCE e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_EUDR_COMPLIANT), 2) AS AVG_EUDR_COMPLIANT,
  ROUND(AVG(f.KPI_MSPO_CERTIFIED), 2) AS AVG_MSPO_CERTIFIED,
  ROUND(AVG(f.KPI_DUE_DILIGENCE_PENDING), 2) AS AVG_DUE_DILIGENCE_PENDING,
  ROUND(AVG(f.KPI_SATELLITE_MONITORING), 2) AS AVG_SATELLITE_MONITORING,
  ROUND(AVG(f.KPI_DEFORESTATION_FREE), 2) AS AVG_DEFORESTATION_FREE,
  ROUND(AVG(f.KPI_GPS_MAPPED_PLOTS), 2) AS AVG_GPS_MAPPED_PLOTS
FROM RAW.SUPPLY_CHAIN_EVENTS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_EUDR_COMPLIANT) AS KPI_EUDR_COMPLIANT, AVG(KPI_MSPO_CERTIFIED) AS KPI_MSPO_CERTIFIED, AVG(KPI_DUE_DILIGENCE_PENDING) AS KPI_DUE_DILIGENCE_PENDING, AVG(KPI_GPS_MAPPED_PLOTS) AS KPI_GPS_MAPPED_PLOTS, AVG(KPI_SATELLITE_MONITORING) AS KPI_SATELLITE_MONITORING, AVG(KPI_DEFORESTATION_FREE) AS KPI_DEFORESTATION_FREE FROM RAW.SUPPLY_CHAIN_EVENTS),
     en AS (SELECT SUM(KPI_SMALLHOLDERS_MAPPED) AS KPI_SMALLHOLDERS_MAPPED FROM RAW.MPOB_REFERENCE)
  SELECT 1 AS SORT_ORDER, 'EUDR Compliant' AS TITLE, KPI_EUDR_COMPLIANT AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_EUDR_COMPLIANT)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'MSPO Certified' AS TITLE, KPI_MSPO_CERTIFIED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_MSPO_CERTIFIED)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Smallholders Mapped' AS TITLE, KPI_SMALLHOLDERS_MAPPED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_SMALLHOLDERS_MAPPED) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Due Diligence Pending' AS TITLE, KPI_DUE_DILIGENCE_PENDING AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DUE_DILIGENCE_PENDING)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'GPS-Mapped Plots' AS TITLE, KPI_GPS_MAPPED_PLOTS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_GPS_MAPPED_PLOTS)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Satellite Monitoring' AS TITLE, KPI_SATELLITE_MONITORING AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SATELLITE_MONITORING)) AS DECIMAL(38,0))) || '/7' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Deforestation-Free' AS TITLE, KPI_DEFORESTATION_FREE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DEFORESTATION_FREE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
