-- ============================================================================
-- 99_RESET.SQL — Reset EUDR Sustainability Compliance to clean demo state
-- ============================================================================
USE DATABASE PALM_OIL_EUDR;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_PARSE_NEW_DOCS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_COMPLIANCE SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_ICEBERG SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.PLANTATION_COMPLIANCE_STATUS REFRESH;
ALTER DYNAMIC TABLE CURATED.CERTIFICATION_TIMELINE REFRESH;
ALTER DYNAMIC TABLE CURATED.SUPPLY_CHAIN_TRACEABILITY REFRESH;
ALTER DYNAMIC TABLE CURATED.DEFORESTATION_RISK_SCORE REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM PALM_OIL_EUDR.RAW.PLANTATIONS → 200
-- SELECT COUNT(*) FROM PALM_OIL_EUDR.RAW.CERTIFICATIONS → 1500
-- SELECT COUNT(*) FROM PALM_OIL_EUDR.RAW.SUPPLY_CHAIN_EVENTS → 50000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_REFRESH_ICEBERG RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_COMPLIANCE RESUME;
ALTER TASK IF EXISTS APP.TASK_PARSE_NEW_DOCS RESUME;
